export function cn(...classes: Array<string | false | null | undefined>): string {
  return classes.filter(Boolean).join(" ");
}

export function countWords(text: string): number {
  return text
    .trim()
    .split(/\s+/)
    .filter(Boolean).length;
}

export function createReferenceNumber(date = new Date()): string {
  const year = date.getFullYear();
  const serial = String(Math.floor(Math.random() * 90000) + 10000);
  return `EX-${year}-${serial}`;
}

export function formatOfficialDate(date = new Date()): string {
  return new Intl.DateTimeFormat("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(date);
}

export function buildShareText(excuse: string): string {
  return [
    "My officially approved excuse:",
    "",
    `“${excuse}”`,
    "",
    "Generated by Excuse Me — a service of the Department of No.",
  ].join("\n");
}

export function pickRandom<T>(items: readonly T[]): T {
  if (items.length === 0) {
    throw new Error("Cannot pick from an empty list.");
  }

  const index = Math.floor(Math.random() * items.length);
  return items[index]!;
}
